### ISSUE TITLE
Parallel build failures, netcdf-fortran 4.5.2

### ISSUE THREAD

**Issue by Dave-Allured** [Unidata/netcdf-fortran#208] opened 2020-01-08 03:01 UTC
### Configuration

* netcdf-fortran 4.5.2
* netcdf-c 4.7.3
* HDF5 1.10.5
* gfortran 9.2
* Mac OS 10.14.6
* Xcode multiple versions: 10.2.1, 11.3
* Macports 2.6.2 build environment

### Summary

Macports likes to use parallel builds for everything, except when told otherwise.  In my Mac environment, it uses `make -j20`.  This works well for most things.

Macports upgraded from netcdf-fortran 4.4.5 to 4.5.2 on 2019 November 16.  Since then, I have experienced several build failures with semi-random behavior, with Macports parallel builds.  The specific error is always some missing internal module file, but the particular missing file changes each time.

### Steps to reproduce

* Create a private install directory on an Intel Mac.
* Install Macports 2.6.2 in the private directory.
* Install netcdf 4.7.3 and all dependencies in the private directory.
* `port -v install netcdf-fortran` -- Invokes a source build.

I am not sure the private install directory is needed.  However, so far this is the only configuration that has reproduced the problem for me.

I can not offer a more simple reproducer at this time.  I naively tried a couple of stand-alone parallel builds with `make -j20`, but this did not trigger any build failures.

The above _steps to reproduce_ is extremely tedious, step 3 in particular.  I do not recommend trying it.  As an alternative, I will offer to test possible patches or strategies if you will post them here.  Or contact me privately.

Here are sample **first** error messages from three build attempts, spaced out over a month.
```
:info:build f951: Fatal Error: Cannot rename module file 'netcdf_nf_data.mod0' to 'netcdf_nf_data.mod': No such file or directory
:info:build Fatal Error: Cannot open module file 'netcdf_fortv2_c_interfaces.mod' for reading at (1): No such file or directory
:info:build f951: Fatal Error: Cannot rename module file 'netcdf4_nc_interfaces.mod0' to 'netcdf4_nc_interfaces.mod': No such file or directory
```

**Comment by Dave-Allured** [comment] 2020-01-08 03:17
Attached are the complete build logs from two separate build attempts that encounter this failure.
* [1202d.main.log](https://github.com/Unidata/netcdf-fortran/files/4033451/1202d.main.log)
* [0106h.main.log](https://github.com/Unidata/netcdf-fortran/files/4033459/0106h.main.log)

**Comment by Dave-Allured** [comment] 2020-01-08 03:21
A workaround under Macports is to disable parallel building for this package:
```
port -v install netcdf-fortran build.jobs=1
```

**Comment by WardF** [comment] 2020-01-09 18:11
Thanks; looking at this now, there appears to be a check added that needs to be tweaked.  I'll try to get a fix for this out ASAP.

**Comment by Dave-Allured** [comment] 2020-01-14 23:00
@WardF, it seems that your changes in PR #210 are for building a target library with MPI support.  This is not related to the `make` option **"-j"** for parallel builds, which runs individual compile commands in sub-processes to speed up the overall build process.  This requires proper traversal of dependencies, in particular both *.o and *.mod files resulting from each fortran source file.

This may be confused by the vagueness of the expression "parallel build".  Could you please take another look at this?  Thanks.

**Comment by WardF** [comment] 2020-01-14 23:01
@Dave-Allured you're absolutely right, thanks! I had already identified the MPI issue and leapt ahead.  Reopening and will address! Thanks.

**Comment by WardF** [comment] 2020-01-14 23:28
As you point out, this is difficult to reproduce.  I will install macports and see if I can reproduce using that, but I do wonder if the failure is in the 'port' system and not the netCDF build system.  Work was done a while ago to make sure that parallel builds would work, and while I can imagine something could creep back in, I'm surprised that it would only manifest inside of the macports environment.  

I'm continuing to investigate. Thanks!

**Comment by Dave-Allured** [comment] 2020-01-14 23:41
Thanks for re-opening.  I suspect this is a cross-platform make problem, but possibly aggravated inside the macports environment.  In my particular desktop macports environment, this breaks fairly reliably until I invoke the serial build constraint.

If you find macports tedious to get going, I will reiterate my offer to test proposed patches and try to save you some time.

**Comment by WardF** [comment] 2020-01-15 01:45
So a quick question, just to make sure I'm duplicating this as closely as possible.  You do not seem to be invoking `port` with the `-s` flag, but from `man port` I have to specify `-s` in order to get port to build from source.   Also, how do you create the port private directory? I'm digging through the documentation (it's been a long time since I used macports), can you point me in the right direction? Thanks!

**Comment by Dave-Allured** [comment] 2020-01-15 02:07
That is correct, I am not using **port -s** because that is the default when using a non-standard prefix, i.e. private directory.

Please let me get back to you tomorrow with a custom prefix recipe.  I must leave shortly.  Close duplication would be best, but complicated.

Meanwhile, you might try a normal Macports install in /opt/local, including ports gcc9 and netcdf, followed by port -s install for only netcdf-fortran.  I would think that would trigger this parallel make failure, just as easily as with private directory.

**Comment by WardF** [comment] 2020-01-15 02:17
@Dave-Allured thanks; I'm doing the default in `/opt/local`, and have yet to duplicate the error, even specifying build jobs explicitly with `build.jobs=20`.  I'll continue tomorrow, thanks!

**Comment by Dave-Allured** [comment] 2020-01-15 21:23
I am working on a reproducer outside of the Macports environment.  It is messy.  Let me get back to you later.

**Comment by alexeedm** [comment] 2020-01-17 16:29
I've seen the same behavior in my pipeline as well. I'm using HPCCM to create a container with PGI compiler and NetCDF, and the compilation only succeeds when doing `make -j1`.

I've uploaded my Dockerfile. Changing lines 146-147 with -j1 makes the compilation go fine. I'm on Ubuntu 18.04, Intel i7-7800X 6-core CPU

[Dockerfile.txt](https://github.com/Unidata/netcdf-fortran/files/4077713/Dockerfile.txt)

**Comment by edwardhartnett** [comment] 2020-01-17 17:29
What directory is this happening in?

**Comment by Dave-Allured** [comment] 2020-01-17 18:24
Generically, ${build_prefix}/netcdf-4.5.2/fortran.  For specific examples, see either of two log files in the above comment no. 2.  They show the remarkably long build prefixes resulting from the Macports source build system.

**Comment by WardF** [comment] 2020-01-17 19:44
@alexeedm thanks for the docker file; I will build it and see what pops out!

**Comment by Dave-Allured** [comment] 2020-01-17 19:45
I think this problem is failure to properly track fortran 90 module file dependencies (*.mod) within the make file.  Apologies if this is already obvious to some.  In the above log files, it appears that certain individual F90 compile commands are launched simultaneously, when they need to be sequenced.

I suspect the current failure tracks to this particular minor code change, comparing my previous known working version to the current failing version:
```
--- 4.4.5/fortran/Makefile.am	2019-01-31 16:49:26 -0700
+++ 4.5.2/fortran/Makefile.am	2019-09-18 11:29:4 -0600
...
-# Turn off parallel builds in this directory.
-.NOTPARALLEL:
...
```
A quick fix would be to simply restore `.NOTPARALLEL`.  It would be ideal to properly track *.mod file dependencies, but I do not currently know a good recipe for that.

**Comment by WardF** [comment] 2020-01-17 21:02
Thanks @Dave-Allured, I assumed it was something like this in the build system, but without being able to recreate it I wasn't sure.  I'm building the docker image referenced above.  Once I can recreate it reliably, I will modify the build files and test to make sure it's fixed!

**Comment by Dave-Allured** [comment] 2020-01-17 21:54
That's great.  I was not able to thresh out a stand-alone reproducer, so far.  If you have any trouble reproducing in docker, let me know, and I will provide a better macports recipe.

**Comment by WardF** [comment] 2020-01-17 22:00
No problem; the docker image did the trick and has given me something I can test against.  I expect we'll have the fix (and a new release) out shortly.

**Closed** 2020-01-22 17:00 UTC
Labels: area/build/autoconf, area/build/cmake

**Comment by skosukhin** [comment] 2020-02-05 14:11
Here is an automatically generated list of module dependencies for the Makefile:
```make
netcdf_nf_interfaces.mod: module_netcdf_nf_interfaces.$(OBJEXT)
module_netcdf_nf_interfaces.$(OBJEXT): netcdf_nf_data.mod
nf_varmio.$(OBJEXT): netcdf_nc_interfaces.mod
nf_fortv2.$(OBJEXT): netcdf_fortv2_c_interfaces.mod netcdf_nc_interfaces.mod
nf_geninq.$(OBJEXT): netcdf_nc_interfaces.mod
netcdf_nc_data.mod: module_netcdf_nc_data.$(OBJEXT)
nf_attio.$(OBJEXT): netcdf_nc_interfaces.mod
nf_nc4.$(OBJEXT): netcdf4_nc_interfaces.mod
nf_control.$(OBJEXT): netcdf_nc_interfaces.mod
nf_varaio.$(OBJEXT): netcdf_nc_interfaces.mod
nf_varsio.$(OBJEXT): netcdf_nc_interfaces.mod
testEightByteGet.$(OBJEXT): typesizes.mod netcdf.mod
nf_var1io.$(OBJEXT): netcdf_nc_interfaces.mod
typesizes.mod: typeSizes.$(OBJEXT)
netcdf.mod: netcdf4.$(OBJEXT)
netcdf4.$(OBJEXT): typesizes.mod
netcdf_nf_data.mod: module_netcdf_nf_data.$(OBJEXT)
module_netcdf_nf_data.$(OBJEXT): netcdf_nc_data.mod
netcdf4_f03.mod: module_netcdf4_f03.$(OBJEXT)
module_netcdf4_f03.$(OBJEXT): netcdf_nf_interfaces.mod netcdf4_nf_interfaces.mod netcdf_nf_data.mod
nf_genvar.$(OBJEXT): netcdf_nc_interfaces.mod
EightByteIntTest-2.$(OBJEXT): typesizes.mod
nf_dim.$(OBJEXT): netcdf_nc_interfaces.mod
netcdf_f03.mod: module_netcdf_f03.$(OBJEXT)
module_netcdf_f03.$(OBJEXT): netcdf_nf_interfaces.mod netcdf_nf_data.mod
EightByteIntTest.$(OBJEXT): typesizes.mod
nf_nc.$(OBJEXT): netcdf_nc_interfaces.mod
netcdf4_nc_interfaces.mod: module_netcdf4_nc_interfaces.$(OBJEXT)
module_netcdf4_nc_interfaces.$(OBJEXT): netcdf_nc_interfaces.mod
nf_misc.$(OBJEXT): netcdf_nc_interfaces.mod
netcdf4_nf_interfaces.mod: module_netcdf4_nf_interfaces.$(OBJEXT)
module_netcdf4_nf_interfaces.$(OBJEXT): netcdf4_nc_interfaces.mod netcdf_nf_data.mod
netcdf_nc_interfaces.mod: module_netcdf_nc_interfaces.$(OBJEXT)
module_netcdf_nc_interfaces.$(OBJEXT): netcdf_nc_data.mod
netcdf.mod: netcdf.$(OBJEXT)
netcdf.$(OBJEXT): typesizes.mod
nf_vario.$(OBJEXT): netcdf_nc_interfaces.mod
nf_genatt.$(OBJEXT): netcdf_nc_interfaces.mod
netcdf_fortv2_c_interfaces.mod: module_netcdf_fortv2_c_interfaces.$(OBJEXT)
module_netcdf_fortv2_c_interfaces.$(OBJEXT): netcdf_nc_interfaces.mod
```

I assume that there are no `USE` statements surrounded by `#ifdef/#endif` directives, are there? I am sure that not all the rules are really needed to enable parallel building, so one might need to go through the list and pick the relevant ones.

**Comment by edwardhartnett** [comment] 2020-03-20 18:37
I believe I have a PR which corrects the missing dependencies; I am about to put it up.

If anyone would like to give it a try and ensure that I got them all, that would be very helpful!

**Comment by Dave-Allured** [comment] 2020-03-22 00:23
I can test in macports, if you would briefly educate me on how to set up for autotools.  I am github impaired.  I used the zip file option to download master just now.  I am stuck because "configure" is not yet generated.  Thanks for your help.

**Comment by edhartnett** [comment] 2020-03-22 01:12
It's very simple if you have the tools installed. After you clone the repo,
go into the netcdf-fortran directory and do:

autoreconf -i

That will give you the configure file and all the trimmings needed for a
normal build. So my normal netcdf-fortran build is something like:

autoreconf -i && CPPFLAGS=-I/usr/local/netcdf-c-4.7.3/include
LDFLAGS=-L/usr/local/netcdf-c-4.7.3/lib ./configure && make -j check

If you don't have the tools installed, you need to first install autoconf,
automake, and libtool. On ubuntu I can do that with something like:

sudo apt-get autoconf automake libtool

Let me know if you need more help.

**Comment by Dave-Allured** [comment] 2020-03-22 19:10
@edhartnett, autoreconf -i worked.  Thank you.
```
configure: error: netcdf-c version 4.7.4 or greater is required
```
Are you planning to include **netcdf-c** backward compatibly in the new version of **netcdf-fortran?**

**Comment by edhartnett** [comment] 2020-03-22 20:35
No. Because the C API has changed, netcdf-fortran requires the latest C
API. Older versions of the C API will not work.

**Comment by Dave-Allured** [comment] 2020-03-22 20:51
Hmmm.  In that case, what is your advice for capturing a buildable pre-release version of 4.7.4 for testing only?  I could grab the current master, but do you advise something better?

**Comment by edhartnett** [comment] 2020-03-22 21:53
No, that's what you must do, build netcdf-c master.

Just clone it, then do:

autoreconf -i

The run configure as normal...

**Comment by Dave-Allured** [comment] 2020-03-23 14:13
Okay, I installed netcdf-C 4.7.4-development from master.

Then parallel build of netcdf-fortran completed properly for two tries under Macports with -j20.  Then it failed on the third try.  Snapshot was March 21, netcdf-fortran master.  See attached console log and build log.
```
Fatal Error: Cannot rename module file 'netcdf4_f03.mod0' to 'netcdf4_f03.mod': No such file or directory
```
[install.ncfort.453x.0323f.repeat.log](https://github.com/Unidata/netcdf-fortran/files/4369829/install.ncfort.453x.0323f.repeat.log)
[main.log.0323f.fail.txt](https://github.com/Unidata/netcdf-fortran/files/4369796/main.log.0323f.fail.txt)

**Comment by skosukhin** [comment] 2020-03-23 14:28
Unfortunately, `master` of `netcdf-fortran` is a bit broken with regard to parallel building (see #238). As far as I remember, this particular error with module file renaming is caused by the fact that the dependencies mention `.$(OBJEXT)` files instead of `.lo` files, which triggers concurrent compilation of the same source file: by the time one of the processes tries to generate `netcdf4_f03.mod`, another one has already removed temporary file `netcdf4_f03.mod0`.

**Comment by edwardhartnett** [comment] 2020-03-23 15:52
OK, good to know. I was wondering whether .$(OBJEXT) should be .lo. 

Does anyone have a reference that authoritatively says to use .lo?
