### ISSUE TITLE
Fails to build with gcc 10

### ISSUE THREAD

**Issue by opoplawski** [Unidata/netcdf-fortran#212] opened 2020-01-23 03:01 UTC
gcc 10 has landed in Fedora Rawhide.  gfortran 10 now enforces type matching in at least some function calls.  netcdf-fortran 4.5.2 fails with:
```
netcdf4_func.f90:730:75:
......
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/REAL(8)).
netcdf4_func.f90:720:75:
......
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(8)/REAL(8)).
netcdf4_func.f90:710:74:
......
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/REAL(8)).
netcdf4_func.f90:700:73:
......
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(2)/REAL(8)).
netcdf4_func.f90:690:73:
......
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(1)/REAL(8)).
netcdf4_func.f90:670:75:
......
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/REAL(8)).
netcdf4_func.f90:660:75:
......
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(8)/REAL(8)).
netcdf4_func.f90:650:74:
......
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/REAL(8)).
netcdf4_func.f90:640:73:
......
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(2)/REAL(8)).
netcdf4_func.f90:630:73:
......
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(1)/REAL(8)).
```

**Comment by WardF** [comment] 2020-01-23 23:36
Thanks @opoplawski for highlighting this, I don't think any of our systems are using gcc/gfortran 10.  I'll take a look.

**Comment by WardF** [comment] 2020-01-28 21:13
It looks like gcc 10 hasn't yet been released? gcc.gnu.org still lists the 9.x branch as the latest stable release.  I'll get gcc10 installed and play around with it, thanks for bringing this to our attention, it will be great to get ahead of this before gcc 10 is formally released!

**Comment by opoplawski** [comment] 2020-01-28 21:17
Correct.  Fedora moves to the next gcc release just before it is fully supported as a major test for both :)

**Comment by WardF** [comment] 2020-01-28 21:17
I see now that Rawhide is the development release; I'm spinning up a VM to work on with it :)

**Comment by musinsky** [comment] 2020-03-17 17:11
https://gcc.gnu.org/gcc-10/changes.html (see Fortran section)
Maybe this help: "Use the new option `-fallow-argument-mismatch` to turn these errors into warnings"

**Comment by han190** [comment] 2020-05-03 03:00
@musinsky Thanks for the tips. The issue exists and can be fixed by your work-around. Just `./configure` with
```shell
export FCFLAGS="-w -fallow-argument-mismatch -O2"
export FFLAGS="-w -fallow-argument-mismatch -O2"
```

**Comment by fxcoudert** [comment] 2020-05-09 21:05
GCC 10.1.0 is released. This issue is appearing on macOS as well, as part of Homebrew testing: https://github.com/Homebrew/homebrew-core/pull/54364/checks?check_run_id=659130100

**Comment by WardF** [comment] 2020-05-11 16:31
I am looking at this and discussing it internally.  Out of curiosity, does NAG or any other Fortran compiler raise a warning/error re: argument mismatch, in line with gcc/gfortran?

**Comment by WardF** [comment] 2020-05-11 19:33
I think that short-term we will need to use these flags to compile, although I'm open to other solutions.  I'll update the documentation and look at defining default flags for gfortran 10, and then we can proceed with the netCDF-Fortran release.

**Comment by danrosen25** [comment] 2020-05-20 17:36
Why don't you overload 'Function nf_def_var_fill' in fortran/nf_nc4.f90 with one interface for a fill_value of typekind Character(KIND=C_CHAR) and other interface for fill_value of typekind integer(kind=OneByteInt), integer(kind=TwoByteInt), integer(kind=FourByteInt), integer(kind=EightByteInt), real(kind=FourByteReal), real(kind=EightByteReal)

Right now the call to nf_def_var_fill in fortran/netcdf4_func.f90 on line 630 is passing a fill_value of typekind integer(kind=OneByteInt) which isn't supported by nf_def_var_fill. According to the netcdf guide nc_def_var_fill takes a fill_value of type void but the fill_value must be the same type as the variable.
[https://www.unidata.ucar.edu/software/netcdf/docs/group__variables.html#gabe75b6aa066e6b10a8cf644fb1c55f83](https://www.unidata.ucar.edu/software/netcdf/docs/group__variables.html#gabe75b6aa066e6b10a8cf644fb1c55f83)

**Closed** 2020-06-02 22:47 UTC

**Comment by kvijaykiran** [comment] 2020-06-03 20:57
> @musinsky Thanks for the tips. The issue exists and can be fixed by your work-around. Just `./configure` with
> 
> ```shell
> export FCFLAGS="-w -fallow-argument-mismatch -O2"
> export FFLAGS="-w -fallow-argument-mismatch -O2"
> ```

How are these flags passed in CMakeLists.txt for use with Visual Studio ? I'm using mingw 64, and the VS simply won't recognize them. Here's what I have in my CMakeLists.txt.

```
cmake_add_fortran_subdirectory(src 
		PROJECT SNOPT 
		LIBRARIES snopt
		LINK_LIBRARIES
		LINK_LIBS snopt
		CMAKE_COMMAND_LINE "-DFCFLAGS=-w -fallow-argument-mismatch -O2"
		NO_EXTERNAL_INSTALL)
```

**Comment by WardF** [comment] 2020-06-03 21:46
@kvijaykiran which compiler are you using with visual studio for Fortran compilation?  You mention you're using mingw, which is a gcc-based compiler, but you're using it integrated with Visual Studio? Can you talk about how you're doing that, a little bit? I can try to replicate it here.

**Comment by kvijaykiran** [comment] 2020-06-03 22:36
@WardF Sorry, I should have added more info.

I was using MSYS2 MinGW-w64's gfortran to compile some Fortran code and build libraries on Windows 10. The gfortran version that comes with it is 10.1.0. I ended up seeing type mismatch errors as @opoplawski originally posted. I added the FCFLAGS and FFLAGS like @han190 indicated within the Makefile, and I was successfully able to get my code to compile and build .a libraries. However, my goal was to build these libraries using Visual Studio to generate .lib files, which are to be used in another project, but I do not have access to a native Fortran compiler (e.g., Intel Visual Fortran).

I came across some documentation here (https://www.netlib.org/lapack/lawnspdf/lawn270.pdf) that it is possible to trick Visual Studio to use MinGW gfortran compiler through using `cmake_add_fortran_subdirectory(...)`. See page 10 and 11 within the PDF. I wanted to pass the `FCFLAGS `and `FFLAGS `to convert Fortran code type mismatch errors into warnings. I thought that simply assigning the flags to `CMAKE_COMMAND_LINE ` would work. It didn't work, and I've been scratching my head for two days on this. I admit my experience with CMakeLists is between noob and intermediate. If passing the flags worked with Makefile build, it should work with Visual Studio too. Here's my latest contraption in my CMakeLists that follows the documentation from the PDF, that didn't work:

```
cmake_minimum_required(VERSION 3.8.2)

project(winsnopt)

SET(CMAKE_Fortran_FLAGS "FCFLAGS=-w -fallow-argument-mismatch -O2 FFLAGS=-w -fallow-argument-mismatch -O2")

include(CMakeAddFortranSubdirectory)

cmake_add_fortran_subdirectory(src 
		PROJECT SNOPT 
		LIBRARIES snopt
		LINK_LIBRARIES
		LINK_LIBS snopt
		CMAKE_COMMAND_LINE
		-DCMAKE_Fortran_FLAGS=${CMAKE_Fortran_FLAGS}
		NO_EXTERNAL_INSTALL)
...
```
I hope I was clear. Thanks for looking into this. Any help is appreciated.

**Comment by PerBergFCOO** [comment] 2020-07-31 12:22
Did anyone actually try the "-fallow-argument-mismatch" option? I mean, it works by turning the errors into warnings (not resolving anything), and compilation of netcdf-f v.4.5.2 with gfortran v10.1.0 will then run to the end. But the result is useless.

That is, "configure" followed by "make" will not complain too much, and one can then do a "make install". But if you do a "make check" instead of just "make", it will (of course) not pass the tests. If you try to avoid the tests, and just do the "make"+"make install", and then when you try to build a code that includes netcdf-f, you will (of course) get "undefined references" in libnetcdff.so corresponding to each of the components that you were warned about (i.e. those that previously failed when errors were treated as errors

V.4.5.2 works fine, by the way, with Intel ifort v.19.1.0.166 which is the latest Intel version I have tested.
I am now testing gfortran v.9.3.0 (i.e. one step back from the latest and greatest version) and will eventually try that with netcdf-f v.4.5.2 (it takes forever to build GCC).


Oh, why didn't I switch to v.4.5.3? Because it doesn't solve it either.
I have netcdf-c v.4.7.4 which is required:
$ nc-config  --version
netCDF 4.7.4

but configure in v.4.7.4 bails out with:
configure: error: netcdf-c version 4.7.4 or greater is required

So, not much luck there.

**Comment by DennisHeimbigner** [comment] 2020-07-31 16:25
> But if you do a "make check" instead of just "make", it will (of course) not pass the tests. 
This is surprising; what kinds of failures are you seeing? Can you characterize them?

**Comment by PerBergFCOO** [comment] 2020-08-03 08:31
Sorry for my late reply (was AFK for an extended weekend).

I came a little longer by turning errors into warnings ("-fallow-argument-mismatch" option), but still "make check" fails with these three (possibly not related to the original issue here):

../fortran/.libs/libnetcdff.so: undefined reference to `nc_def_var_szip'
../fortran/.libs/libnetcdff.so: undefined reference to `nc_inq_var_filter'
../fortran/.libs/libnetcdff.so: undefined reference to `nc_open_mem'

I get the same three when I try to link any fortran code to libnetcdff 
Any idea what I am missing? 
As said, it works fine for me with pretty new Intel compiler, but not with GNU.

**Comment by PerBergFCOO** [comment] 2020-08-03 10:27
BOMMER! 
Found the reason for the undefined refernces: By mistake, I linked against an old system installed "/usr/lib64/libnetcdf.so" not the newly installed "/opt/netcdf-4.7.4/gcc-netcdf4/lib/libnetcdf.so".

"make"+"make install" then works with the "-fallow-argument-mismatch" option.

But the "make check" will fail with many "type mismatch" errors like:
nf_test/ftest.F:1436:33:
 1433 |       call ncvgt1(ncid, bid, ix, b, iret)
      |                                 2
......
 1436 |       call ncvgt1(ncid, sid, ix, s, iret)
      |                                 1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(2)/INTEGER(1)).

It seems to me, that the "-fallow-argument-mismatch" option is not carried on to the tests?

**Comment by DennisHeimbigner** [comment] 2020-08-03 15:46
Did you use -fallow-argument-mismatch when building netcdf-c as well as netcdf-fortran?
Or are you using a prebuilt netcdf-c?

**Comment by PerBergFCOO** [comment] 2020-08-04 05:52
No, I did not use --fallow-argument-mismatch when building netcdf-c.
I built the netcdf-c vers.4.7.4 lib some weeks ago, when I didn't know about this issue, because I needed it to update netcdf-f to v.4.5.2 for the Intel vers.19.1.0.166 (which worked nicely).

**Comment by PerBergFCOO** [comment] 2020-08-04 06:41
... and the compiler option "--fallow-argument-mismatch" works with Fortran, but not with C:

$ gcc --version | head -1
gcc (GCC) 10.1.0
$gcc --fallow-argument-mismatch HelloWorld.c 
gcc: error: unrecognized command-line option ‘--fallow-argument-mismatch’; did you mean ‘-fallow-argument-mismatch’?
$ gcc -fallow-argument-mismatch HelloWorld.c 
cc1: warning: command-line option ‘-fallow-argument-mismatch’ is valid for Fortran but not for C

**Comment by ArchangeGabriel** [comment] 2020-08-04 20:38
I thought I had posted about this days ago, but apparently not. I can confirm that the test suite (or at least part of it) is failing unless I add `-fallow-argument-mismatch` to FCFLAGS/FFLAGS (https://github.com/archlinux/svntogit-community/blob/packages/netcdf-fortran/trunk/PKGBUILD).

**Comment by PerBergFCOO** [comment] 2020-08-05 05:52
Thanks! That did it.
Previously, I added `-fallow-argument-mismatch` to FCFLAGS and passed that to `configure`. I was not aware that (some of) the tests need FFLAGS. So, adding `-fallow-argument-mismatch` to FFLAGS too and passing it to `configure` will pass the tests with `make check`.

**Comment by habtie-phy** [comment] 2021-03-13 15:03
> @musinsky Thanks for the tips. The issue exists and can be fixed by your work-around. Just `./configure` with
> 
> ```shell
> export FCFLAGS="-w -fallow-argument-mismatch -O2"
> export FFLAGS="-w -fallow-argument-mismatch -O2"
> ```

Hi,
Could you elaborate more. I just copy and paste the above commands, but still not working. Thank you!

**Comment by habtie-phy** [comment] 2021-03-14 10:04
> @musinsky Thanks for the tips. The issue exists and can be fixed by your work-around. Just `./configure` with
> 
> ```shell
> export FCFLAGS="-w -fallow-argument-mismatch -O2"
> export FFLAGS="-w -fallow-argument-mismatch -O2"
> ```

Hi 
Could you elaborate it more. I just made a copy and past of the above two commands on the Terminal of Ubuntu 18.04. The problem still persists. I feel like I had to combine them with the ./configure command. but How can I do that? could you present the whole step here? Thanks!

**Comment by PerBergFCOO** [comment] 2021-03-15 07:00
Hi,


Here's what worked for me (I use modules):


First, build and install the NETCDF C library

Then, you are ready to build and install the NETCDF fortran library with gfortran:

NCVER=4.7.4
STAGINGAREA=/scratch/$USER/staging_area_NOBACKUP
SRCDIR=$STAGINGAREA/src/NETCDF
WORKDIR=$STAGINGAREA/wrk/

CC=gcc
module purge
module load netcdf-c/${NCVER}/netcdf4
NCDIR=/opt/netcdf-${NCVER}/${CC}-netcdf4

NFVER=4.5.2
cd $SRCDIR
tar -zxvf netcdf-fortran-${NFVER}.tar.gz
INSTALL_DIR=/opt/netcdf-fortran-${NFVER}

COMPNAM=gfortran
COMPVER=10.1.0
FC=gfortran
F77=gfortran

For compmod=ieee, debug, and fast you build and install separate libraries:


module load ${COMPNAM}/${COMPVER}/${compmod}
echo "======================================================================================="
echo "Building for" ${COMPNAM} ${COMPVER} ${compmod}

cd $WORKDIR
rm -rf $WORKDIR/netcdf-f-${NFVER}
mkdir $WORKDIR/netcdf-f-${NFVER}
cd $WORKDIR/netcdf-f-${NFVER}

NFDIR=${INSTALL_DIR}/${COMPNAM}-${COMPVER}-${compmod}

# remember the extra compiler option:
export FCFLAGS=${FCFLAGS}" -fallow-argument-mismatch"
export FFLAGS=${FCFLAGS}

FC=${FC} F77=${F77} CPPFLAGS="-I${NCDIR}/include" LIBS="-L${NCDIR}/lib -lnetcdf"  ${SRCDIR}/netcdf-fortran-${NFVER}/configure --prefix=${NFDIR} --enable-static

make check
sudo make install

echo " "
echo "======================================================================================="

cheers,
Per

________________________________

**Comment by PerBergFCOO** [comment] 2021-03-15 07:21
Hi again,

Two more lines of info:


Configure needs FCFLAGS but (some of) the tests use FFLAGS so we need to export that too.


compmod=ieee, debug, and fast  are just shorthand notation for the modules for strict ieee flags, debug flags and flags for speed optimization.


Sorry, that I forgot those at first.

Ciao, Per

________________________________

**Comment by Fan142857** [comment] 2021-03-19 05:16
> @musinsky Thanks for the tips. The issue exists and can be fixed by your work-around. Just `./configure` with
> 
> ```shell
> export FCFLAGS="-w -fallow-argument-mismatch -O2"
> export FFLAGS="-w -fallow-argument-mismatch -O2"
> ```



> @musinsky Thanks for the tips. The issue exists and can be fixed by your work-around. Just `./configure` with
> 
> ```shell
> export FCFLAGS="-w -fallow-argument-mismatch -O2"
> export FFLAGS="-w -fallow-argument-mismatch -O2"
> ```

I am sorry, I am a freshman at GCC compiler. So my platform is MacOS, and I am wondering can anyone of you show me the details of how to do this 'export' part in the terminal.

**Comment by han190** [comment] 2021-03-19 23:33
Hi, @Fan142857. You don't have to any `export` now since the latest [release](https://github.com/Unidata/netcdf-fortran/releases/tag/v4.5.3) has this issue resolved.

**Comment by Fan142857** [comment] 2021-03-22 06:35
> Hi, @Fan142857. You don't have to any `export` now since the latest [release](https://github.com/Unidata/netcdf-fortran/releases/tag/v4.5.3) has this issue resolved.

Thank you for your reply. But I see the [release](https://github.com/Unidata/netcdf-fortran/releases/tag/v4.5.3) which I still don't get it. Can you show me the procedure to do that. (I'm kind of a freshman at using gcc to compile fortran and don't know much about macOS terminal language)
